version: '3.4'

services:

    site:
        image: ${DOCKER_REGISTRY:-noahsmart}/noah.spa:${PLATFORM:-linux}-${TAG:-latest}
        container_name: noah.spa
        build:
          context: ./src/Frontend/
          dockerfile: ./Dockerfile
        depends_on:
          - identityservice
          - webapi

    webapi:
        image: ${DOCKER_REGISTRY:-noahsmart}/noah.webapi:${PLATFORM:-linux}-${TAG:-latest}
        container_name: noah.webapi
        restart: always
        build:
          context: .
          dockerfile: ./src/Noah.WebAPI/Dockerfile
        depends_on:
         - influxdb
         - identityservice
         - mongo
        networks:
         - bridge-network


    mongo:
        image: mongo:latest
        restart: unless-stopped
        container_name: mongo
        networks:
          - bridge-network
        volumes:
          - mongodb:/data/db
          - mongodb_config:/data/configdb

    mongo.express:
        image: mongo-express
        restart: always
        links:
          - mongo
        depends_on: 
         - mongo
        networks:
          - bridge-network
        

volumes:
    mongodb:
    mongodb_config:
    
networks: 
    bridge-network:
        driver: bridge